### ISSUE TITLE
google play

### ISSUE THREAD

**Issue by fightlord** [yonggekkk/replit-xray#10]
地点改为印度后发现手机在google play上不能更新APP，浏览网页什么的都可以，换一个其他地区的节点就可以，有办法解决吗？

**Comment by yonggekkk** [comment]
你app不支持印度区？明天更新下支持美区

**Comment by fightlord** [comment]
解决了，要把google play原来设置的付款信息中的中国地址信息删除，因为谷歌市场不能在中国使用
