### ISSUE TITLE
新页面二维码无法显示

### ISSUE THREAD

**Issue by Copy2Translator** [yonggekkk/replit-xray#11]
 ./python/main.sh
./python/main.sh: line 155: qrencode: command not found
base64: qrcode.png: No such file or directory
./python/main.sh: line 163: qrencode: command not found
base64: qrcode.png: No such file or directory
./python/main.sh: line 171: qrencode: command not found
base64: qrcode.png: No such file or directory

**Comment by yonggekkk** [comment]
项目重新run下，不行就新建项目上传

**Comment by Copy2Translator** [comment]
重新run依旧报错，删了新建又出现新的问题，直接提示无法唤醒
![Snipaste_2023-02-27_10-18-58](https://user-images.githubusercontent.com/75414580/221457124-38055f24-cb3a-4414-96ee-6919f42eaf3a.png)

**Comment by yonggekkk** [comment]
> 重新run依旧报错，删了新建又出现新的问题，直接提示无法唤醒 ![Snipaste_2023-02-27_10-18-58](https://user-images.githubusercontent.com/75414580/221457124-38055f24-cb3a-4414-96ee-6919f42eaf3a.png)

上传时，要等到覆盖提示后才能点run

**Comment by Copy2Translator** [comment]
> 

又新建了一遍，现在又是这个提示了
![Snipaste_2023-02-27_10-24-06](https://user-images.githubusercontent.com/75414580/221457542-95c8cb6e-b8a3-40aa-adbf-4c2ec497d2e2.png)

**Comment by Copy2Translator** [comment]
> 



> > 重新 run 依旧报错，删了新建又出现新的问题，直接提示无法唤醒 ![Snipaste_2023-02-27_10-18-58](https://user-images.githubusercontent.com/75414580/221457124-38055f24-cb3a-4414-96ee-6919f42eaf3a.png)
> 
> 上传时，要等到覆盖提示后才能点 run

我又重新弄了一遍，还是提示无法唤醒
![Snipaste_2023-02-27_10-29-11](https://user-images.githubusercontent.com/75414580/221459449-2a3baf54-ee3e-4262-bf56-a887679f7876.png)
![Snipaste_2023-02-27_10-29-39](https://user-images.githubusercontent.com/75414580/221459482-c767c641-2113-4706-b007-7e19d73edb41.png)

**Comment by yonggekkk** [comment]
我试了没问题，你新建一个Blank Repl

**Comment by Copy2Translator** [comment]
> 

我知道问题出在哪里了，如果新建名字不改变，还是用原来的，就会出现我上面的情况
