### ISSUE TITLE
replit设置了www变量但是伪装网页没有更改

### ISSUE THREAD

**Issue by laboriouslyx** [yonggekkk/Replit-Xray#14]

**Comment by yonggekkk** [comment]
要等一段时间！半小时吧

**Comment by laboriouslyx** [comment]
那个我已经用echo $www验证了，变量已更改，但是还是没办法，后来有出现了403

**Comment by laboriouslyx** [comment]
![image](https://user-images.githubusercontent.com/116939188/222961965-21aff6f7-a85a-4cf2-b7f0-85976cbc3385.png)
![image](https://user-images.githubusercontent.com/116939188/222961992-0e15cf0c-c545-4b44-9f9e-a99bde9a1300.png)
![image](https://user-images.githubusercontent.com/116939188/222962003-3bc74fe9-3a0d-44be-827c-1e65f97f3eb4.png)

**Comment by laboriouslyx** [comment]
还有每个伪装页面分别是什么啊
和doprax一样吗
我想要这个
![image](https://user-images.githubusercontent.com/116939188/222962088-5fbe6916-37c9-4511-8caf-0556a7961997.png)

**Comment by yonggekkk** [comment]
> 还有每个伪装页面分别是什么啊 和doprax一样吗 我想要这个 ![image](https://user-images.githubusercontent.com/116939188/222962088-5fbe6916-37c9-4511-8caf-0556a7961997.png)

一样

**Comment by yonggekkk** [comment]
> _No description provided._

脚本更新了下，新建个项目试试吧，现在更改伪装网页变化速度快了
