### ISSUE TITLE
印度区也不行了

### ISSUE THREAD

**Issue by quan9364** [yonggekkk/Replit-Xray#15]
一早起来提示违反政策无法运行

**Comment by yonggekkk** [comment]
> 一早起来提示违反政策无法运行

是现在最新版本吗？

**Comment by quan9364** [comment]
谢谢回复，用最新版本又满血复活了On Mar 11, 2023, at 12:21, 甬哥侃侃侃ygkkk ***@***.***> wrote:﻿

一早起来提示违反政策无法运行

是现在最新版本吗？

**Comment by yonggekkk** [comment]
> 谢谢回复，用最新版本又满血复活了On Mar 11, 2023, at 12:21, 甬哥侃侃侃ygkkk ***@***.***> wrote:﻿ 一早起来提示违反政策无法运行 是现在最新版本吗？ —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

重新下载上传即可

**Comment by quan9364** [comment]
感谢大佬！爱你On Mar 11, 2023, at 13:32, 甬哥侃侃侃ygkkk ***@***.***> wrote:﻿

谢谢回复，用最新版本又满血复活了On Mar 11, 2023, at 12:21, 甬哥侃侃侃ygkkk @.> wrote:﻿ 一早起来提示违反政策无法运行 是现在最新版本吗？ —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: @.>

重新下载上传即可
