### ISSUE TITLE
今天收到邮件通知，从4.7开始每个账户每个月限流10G

### ISSUE THREAD

**Issue by quan9364** [yonggekkk/Replit-Xray#16]
Hey there,

In our ongoing effort to provide the best experience for our entire community, we're introducing data transfer limits on all Replit accounts, effective April 7th. These new limits will help us combat abuse and ensure that our platform remains accessible and enjoyable for everyone.

Here's a quick overview of the new limits:

Free tier developers: 10 GiB/month
Hacker developers: 50 GiB/month
Pro developers: 100 GiB/month
If you require more data transfer, you can purchase additional outbound data at a rate of $0.10/GiB.

To help you stay within these limits, we recommend optimizing your Repls by:

Reducing WebSocket ping frequency or adopting an event-driven system
Decreasing ping frequency or payload size for uptimers
Utilizing dedicated solutions for video content file-sharing
Removing Repls that serve as proxies, which violate our Terms of Service
The outbound data transfer limits we're introducing should not get in your way, but if you're unsure how to optimize your Repls, please don't hesitate to reach out in [Replit Ask](http://link.mail.replit.com/ls/click?upn=6C3RbwTZ5-2F31fSjC5gMvlHbR4XPfug1PECdvN0xqxltlk-2BnboAg9KdqXZqQ9-2BRxtKTtrfvUb2lDq7Ahch8uNcKxigRUvI-2BuD89OlskKCnsWh8GG-2BdlR9ZA1hhnOZMM3iiGCQR22kHV4R99Y0tXh5bA-3D-3DS-XB_rfMM2XTn5wYESe1ahyRV-2BxZRiDRBwcSfa5zJL7m4xGMKaDpnLGfDWAXddQMaB8LUpWmQjITqm0DEckctBCPjoE2-2BoXQpL-2Bx7D-2FqSKbTv-2FbzZxsd5jKFsU3QfuKTJQHmGXBxsWDGYFZ03fFrFI6NmTQnNWOlxa3RBAJYIhDYj5zUrmtmF0P4taU6Xcf9YSZvVFpSTCrJoBBRThpGjKouVQKyIK2VBPhF-2BaK6djnXKKPGa-2F87gvQFPzHiKZMWqJ7fl-2Bn7VL91xVt19mq0PyxB5wSQrlfG70LY77ssbU5EBclsTHP-2BsBhSYXOkIB1pOmYnwNnmbnjJzxtXMLq9Mm7nxiRZx-2BNFPd7qtUs4OAapA0O0XmbNYzVXWIaXUxrOKoQHFNJJkNKc-2BSSPrLtoezS7tNGK8wusYn-2FfxQM8R9DacZZ0-3D). We're happy to help problem solve and make sure that you're unblocked to do your best work on Replit.

Thank you for your understanding and continued support.

- The Replit Team

**Comment by yonggekkk** [comment]
是的！已收到
