### ISSUE TITLE
最近经常遭遇TCP阻断

### ISSUE THREAD

**Issue by quan9364** [yonggekkk/Replit-Xray#17]
搭建了好多replit，但是最近碰到非常频繁的TCP阻断，具体表现现象为无法连接，在ping.pe上测试，国外的服务器都连的通，国内的服务器都连不通，估计是被GFW伤到了。好在恢复时间很快，用不了几分钟就恢复，但是一天要被TCP阻断好几次，不知道有没有什么办法解决？谢谢大神

**Comment by yonggekkk** [comment]
套cdn吧

**Comment by yonggekkk** [comment]
或者关tls自选IP
参考教程：https://youtu.be/9LlEcV17A34

**Comment by quan9364** [comment]
好的谢谢答复JackySent from my iPhoneOn Apr 1, 2023, at 15:41, 甬哥侃侃侃ygkkk ***@***.***> wrote:﻿
或者关tls自选IP
参考教程：https://youtu.be/9LlEcV17A34
