### ISSUE TITLE
最近好像又不行了

### ISSUE THREAD

**Issue by quan9364** [yonggekkk/Replit-Xray#18]
folk了最新版本，运行也成功，弹出安装完毕！请点击下面白色的网页链接，查看相关协议信息。但是链接点进去是空的

**Comment by yonggekkk** [comment]
等会再试试！应该是暂时性的

**Comment by quan9364** [comment]
这会试了下，伪装网页可以打开，但是v2ray连接时报错the request returned with HTTP status code service unavailable。感觉应该不是被墙，就不知道啥情况JackySent from my iPhoneOn May 4, 2023, at 21:56, 甬哥侃侃侃ygkkk ***@***.***> wrote:﻿
等会再试试！应该是暂时性的

**Comment by quan9364** [comment]
今天又一大批都倒下了，v2ray提示The request returned with HTTP status code Servicel Unavailable

**Comment by yonggekkk** [comment]
> 今天又一大批都倒下了，v2ray提示The request returned with HTTP status code Servicel Unavailable

切到美国节点
