### ISSUE TITLE
今天又一堆节点倒下了

### ISSUE THREAD

**Issue by quan9364** [yonggekkk/Replit-Xray#19]
v2ray提示The request returned with HTTP status code Service Unavailable，不知道是不是官网的问题

**Comment by yonggekkk** [comment]
切换到美国节点

**Comment by quan9364** [comment]
谢谢，已经解决。看了官网说明应该是亚洲服务器坏了。ResolvedAfter 6 hours and 15 minutesWe've now resolved the incident. Thanks for your patience.13:58 PDT - 20 May 2023RecoveringAfter 5 hours and 34 minutesWe've fixed the core issue, and are waiting for things to recover.13:17 PDT - 20 May 2023InvestigatingRepls hosted on the Asia cluster may show an error in the webview or the repl.co webpage. We are very sorry about this and are working quickly to resolve this. We will post an update as soon as we know more.07:42 PDT - 20 May 2023JackySent from my iPhoneOn May 21, 2023, at 04:58, 甬哥侃侃侃ygkkk ***@***.***> wrote:﻿
切换到美国节点
