### ISSUE TITLE
Replit要倒下了

### ISSUE THREAD

**Issue by gittyspirit** [yonggekkk/Replit-Xray#20]
Replit要废了啊！2024年以后他们就要全面收费，取消免费套餐了，怎么办啊！

**Comment by gittyspirit** [comment]
https://blog.replit.com/hosting-changes
他们要修改托管方式了

**Comment by yonggekkk** [comment]
> https://blog.replit.com/hosting-changes 他们要修改托管方式了

没说到取消免费呀

**Comment by gittyspirit** [comment]
>我们的 repl.co、replit.app 和 replit.dev 计划

>2024 年 1 月 1 日，repl.co 域将转换为 replit.dev 域，并且只有在有人在编辑器中时才能访问。如果您当前正在 repl.co 上“托管”任何内容，我们强烈建议您在新年之前迁移到部署。

>Replit.app 仍将是自动缩放、静态和预留 VM 用户获得的高级域。

估计以后要编辑器保活了
