### ISSUE TITLE
https://github.com/yonggekkk/Replit-Xray/raw/main/vmvltrssso-argo.zip   您好，下载这个压缩包之后，压缩包里还是没有 main.sh 文件

### ISSUE THREAD

**Issue by lixiaodongsql** [yonggekkk/Replit-Xray#26]
https://github.com/yonggekkk/Replit-Xray/raw/main/vmvltrssso-argo.zip     您好，下载这个压缩包之后，压缩包里还是没有 main.sh 文件    请问现在  replit  如何保活？谢谢您

**Comment by yonggekkk** [comment]
看项目说明与视频教程
