### ISSUE TITLE
v2rayN V6.33 连接服务器错误

### ISSUE THREAD

**Issue by scanligithub** [yonggekkk/Replit-Xray#27]
too many colons in address

**Comment by scanligithub** [comment]
环境：
1、V2rayN V6.33。
2、Vmess+ws+tls。
3、留空、xray、sing-box切换。
4、测速均为-1。
显示错误信息：
2024/01/28 13:59:40 127.0.0.1:56489 accepted //accounts.google.com:443 [http >> proxy]
2024/01/28 13:59:40 [Warning] [831660927] app/proxyman/outbound: failed to process outbound traffic > proxy/vmess/outbound: failed to find an available destination > common/retry: [transport/internet/websocket: failed to dial WebSocket > transport/internet/websocket: failed to dial to (wss://https://921afa2b-52cf-4f1d-b00d-39b9cbdfab73-00-3dx7kjjc20mef.pike.replit.dev//921afa2b-52cf-4f1d-b00d-39b9cbdfab73-vm):  > dial tcp: address https://921afa2b-52cf-4f1d-b00d-39b9cbdfab73-00-3dx7kjjc20mef.pike.replit.dev/:443: too many colons in address] > common/retry: all retry attempts failed

**Comment by yonggekkk** [comment]
注意：ym变量复制填写时注意检查，不要带https://且末尾不要带/

**Comment by scanligithub** [comment]
正如老大所说，在拷贝伪装网址时，要去掉头部的http://和尾部的/，错误消除。
