### ISSUE TITLE
discord.com 提示证书不正确

### ISSUE THREAD

**Issue by zcr268** [yonggekkk/Replit-Xray#31]
RT
![image](https://github.com/yonggekkk/Replit-Xray/assets/9443858/0ada191b-c81a-4245-b20c-37477e364a4c)

**Comment by yonggekkk** [comment]
replit不存在这问题吧

**Comment by zcr268** [comment]
截图那会我刚用fork 的测试的。google 没问题但是discord 不行。

**Comment by yonggekkk** [comment]
换平台或者浏览器试试

**Comment by zcr268** [comment]
换平台是指换个网站么？

**Comment by yonggekkk** [comment]
> 换平台是指换个网站么？

比如手机或者电脑上
