### ISSUE TITLE
真延迟总是大于 5s，但 Ping 服务器则是几百 ms

### ISSUE THREAD

**Issue by lwtdzh** [yonggekkk/Replit-Xray#34]
感谢yg的脚本，今天部署上去发现一个问题，我测试真连接（多个客户端多个OS，三网都测试过）发现都是5000ms+，但是 ping 服务器都是几百 ms，感觉好像这个脚本里面转发时有个地方 sleep 了一样，其他人有遇到这个问题么？更换美国印度，更换协议都是一样的。

**Comment by yonggekkk** [comment]
这可能是replit机制吧。。没办法
