### ISSUE TITLE
2.11虽然甬哥replit官网重新上传，但仍然报错

### ISSUE THREAD

**Issue by chen-jingliang** [yonggekkk/replit-xray#7]
虽然甬哥replit官网重新上传，但仍然报错
[![screenshot-replit-com-2023-02-11-21-28-03.png](https://i.postimg.cc/763qMbf4/screenshot-replit-com-2023-02-11-21-28-03.png)](https://postimg.cc/VrNyzfqZ)

**Comment by yonggekkk** [comment]
重制下报错文字

**Comment by chen-jingliang** [comment]
 cowsay Configure me!
sh: line 1: cowsay: command not found
exit status 127


**Comment by yonggekkk** [comment]
>  cowsay Configure me! sh: line 1: cowsay: command not found exit status 127  点击 run 后，报错内容如上，请甬哥解决 [![screenshot-replit-com-2023-02-12-08-46-57.png](https://camo.githubusercontent.com/d6f1893e37b1f4220641b594fc635578e3ef71b429bc49599ba61b95fe67d239/68747470733a2f2f692e706f7374696d672e63632f335244546b516e762f73637265656e73686f742d7265706c69742d636f6d2d323032332d30322d31322d30382d34362d35372e706e67)](https://postimg.cc/JDmgFvwr)

https://youtu.be/NdTfaL_NLKw
有5个文件，如果是MAC电脑，谷歌下如何解决 . 开头的文件如何显示

**Comment by chen-jingliang** [comment]
Command+Shift+. 可以显示隐藏文件、文件夹，再按一次，恢复隐藏




675346494
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "yonggekkk/replit-xray"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年2月12日(星期天) 晚上6:48
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [yonggekkk/replit-xray] 2.11虽然甬哥replit官网重新上传，但仍然报错 (Issue #7)





  
 cowsay Configure me! sh: line 1: cowsay: command not found exit status 127  点击 run 后，报错内容如上，请甬哥解决 
  
https://youtu.be/NdTfaL_NLKw
 有5个文件，如果是MAC电脑，谷歌下如何解决 . 开头的文件如何显示

**Comment by chen-jingliang** [comment]
Command+Shift+. 可以显示隐藏文件、文件夹，再按一次，恢复隐藏。显示后上传5个文件可以正常使用。





675346494
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "yonggekkk/replit-xray"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年2月12日(星期天) 晚上6:48
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [yonggekkk/replit-xray] 2.11虽然甬哥replit官网重新上传，但仍然报错 (Issue #7)





  
 cowsay Configure me! sh: line 1: cowsay: command not found exit status 127  点击 run 后，报错内容如上，请甬哥解决 
  
https://youtu.be/NdTfaL_NLKw
 有5个文件，如果是MAC电脑，谷歌下如何解决 . 开头的文件如何显示
