### ISSUE TITLE
显示不能运行

### ISSUE THREAD

**Issue by fightlord** [yonggekkk/replit-xray#8]
安装了一天，就不能运行了。replit显示如下
You can’t run this Repl right now.
This Repl is unavailable at the moment.
If you are the owner of this Repl and believe you should be able to run it, please contact support.

**Comment by dark748001** [comment]
我也是这种的.

**Comment by yonggekkk** [comment]
请先尝试切换地区，美国-印度相互切换几次，如还不成功，尝试重新本地上传

**Comment by fightlord** [comment]
新建本地上传无效，更改地区为印度有效
